PHASE_CONTROL = {
    'paused': {
        'short_name': 'paused',
        'full_name': 'Paused',
        'instructions': 'The deliberation process is temporarily paused.',
        'claim_active': 'active',
        'vote_btn': 'disabled',
        'prioritize_btn': 'disabled',
        'theming_menu': 'hidden',
        'improve_menu': 'hidden',
        'addstmt_btn': 'hidden',
    },
    'not_started': {
        'short_name': 'not_started',
        'full_name': 'Not started',
        'instructions': 'The deliberation is not started yet. Further instructions will be updated here!',
        'document_active': 'active',
        'vote_btn': 'hidden',
        'prioritize_btn': 'hidden',
        'theming_menu': 'hidden',
        'improve_menu': 'hidden',
        'addstmt_btn': 'hidden',
    },
    'tagging': {
        'short_name': 'tagging',
        'full_name': 'Tagging',
        'instructions': 'You\'ll be working on ... Please ... This process will last ...',
        'show_highlight_toolbar': True,
        'document_active': 'active',
        'vote_btn': 'hidden',
        'prioritize_btn': 'hidden',
        'theming_menu': 'hidden',
        'improve_menu': 'hidden',
        'addstmt_btn': 'hidden',
    },
    'nugget': {
        'short_name': 'nugget',
        'full_name': 'Nugget extraction',
        'instructions': 'In this phase you will be working on nuggets extraction. Nuggets are informative pieces in the documents, which could serve the source material for claim construction. To extract a nugget, please ... This process will end on ...',
        'show_highlight_toolbar': True,
        'document_active': 'active',
        'vote_btn': 'hidden',
        'prioritize_btn': 'hidden',
        'theming_menu': 'hidden',
        'improve_menu': 'hidden',
        'addstmt_btn': 'hidden',
    },
    'extract': {
        'short_name': 'extract',
        'full_name': 'Claim construction',
        'instructions': 'The goal of this phase is to build claims out of the nuggets we collaboratively extracted. When you compose a claim, please be sure to make it a clear, coherent and meaningful sentence. Avoid any language that would be difficult to understand by an average citizen.',
        'show_highlight_toolbar': True,
        'document_active': 'active',
        'vote_btn': 'hidden',
        'prioritize_btn': 'hidden',
        'theming_menu': 'hidden',
        'improve_menu': 'hidden',
        'addstmt_btn': 'hidden',
    },
    'categorize': {
        'short_name': 'categorize',
        'full_name': 'Claim categorization',
        'instructions': 'Before we proceed with claim improvement, let\'s category the claims we just composed. Available categories are Pro, Con and Key Finding. If you don\'t think a claim should proceed to the next round, you can also vote a Discard to it. Facilitators will perform the final categorization for each claim.',
        'claim_active': 'active',
        'prioritize_btn': 'hidden',
        'theming_menu': 'hidden',
        'improve_menu': 'hidden',
        'addstmt_btn': 'hidden',
    },
    'theming': {
        'short_name': 'theming',
        'full_name': 'Claim theme identification',
        'instructions': 'You\'ll be working on ... Please ... This process will last ...',
        'claim_active': 'active',
        'vote_btn': 'disabled',
        'prioritize_btn': 'hidden',
        'improve_menu': 'hidden',
        'addstmt_btn': 'hidden',
    },
    'improve': {
        'short_name': 'improve',
        'full_name': 'Claim prioritization and improvement',
        'instructions': 'This phase involves claim consolidation and improvement in terms of information and language. Please use the rewording and merging functions.',
        'claim_active': 'active',
        'vote_btn': 'hidden',
        'theming_menu': 'hidden',
    },
    'finished': {
        'short_name': 'finished',
        'full_name': 'Finished',
        'instructions': 'The deliberation event has ended. Please view the Citizens\' Statement.',
        'show_statement_link': True,
        'claim_active': 'active',
        'vote_btn': 'disabled',
        'prioritize_btn': 'disabled',
        'theming_menu': 'hidden',
        'improve_menu': 'hidden',
        'addstmt_btn': 'hidden',
    }
}