PHASE_CONTROL = {
    'paused': {
        'short_name': 'paused',
        'full_name': 'Paused',
        'instructions': 'The deliberation process is temporarily paused.',
        'claim_active': 'active',
        'vote_btn': 'disabled',
        'prioritize_btn': 'disabled',
        'theming_menu': 'hidden',
        'improve_menu': 'hidden',
    },
    'not_started': {
        'short_name': 'not_started',
        'full_name': 'Not started',
        'instructions': 'The deliberation is not started yet. Further instructions will be updated here!',
        'document_active': 'active',
        'vote_btn': 'hidden',
        'prioritize_btn': 'hidden',
        'theming_menu': 'hidden',
        'improve_menu': 'hidden',
    },
    'tagging': {
        'short_name': 'tagging',
        'full_name': 'Tagging',
        'instructions': 'You\'ll be working on ... Please ... This process will last ...',
        'vote_btn': 'hidden',
        'prioritize_btn': 'hidden',
        'theming_menu': 'hidden',
        'improve_menu': 'hidden',
    },
    'extract': {
        'short_name': 'extract',
        'full_name': 'Claim extraction',
        'instructions': 'You\'ll be working on ... Please ... This process will last ...',
        'show_highlight_toolbar': True,
        'document_active': 'active',
        'vote_btn': 'hidden',
        'prioritize_btn': 'hidden',
        'theming_menu': 'hidden',
        'improve_menu': 'hidden',
    },
    'categorize': {
        'short_name': 'categorize',
        'full_name': 'Claim categorization',
        'instructions': 'You\'ll be working on ... Please ... This process will last ...',
        'claim_active': 'active',
        'prioritize_btn': 'hidden',
        'theming_menu': 'hidden',
        'improve_menu': 'hidden',
    },
    'theming': {
        'short_name': 'theming',
        'full_name': 'Claim theme identification',
        'instructions': 'You\'ll be working on ... Please ... This process will last ...',
        'claim_active': 'active',
        'vote_btn': 'disabled',
        'prioritize_btn': 'hidden',
        'improve_menu': 'hidden',
    },
    'improve': {
        'short_name': 'improve',
        'full_name': 'Claim prioritization and improvement',
        'instructions': 'You\'ll be working on ... Please ... This process will last ...',
        'claim_active': 'active',
        'vote_btn': 'disabled',
        'theming_menu': 'hidden',
    },
    'finished': {
        'short_name': 'finished',
        'full_name': 'Finished',
        'instructions': 'The deliberation event has ended. Please view the statement.',
        'show_statement_link': True,
        'claim_active': 'active',
        'vote_btn': 'disabled',
        'prioritize_btn': 'disabled',
        'theming_menu': 'hidden',
        'improve_menu': 'hidden',
    }
}